function out = convertCppTime(cppSystemTime)
    out = zeros(size(cppSystemTime));
    for i = 1:numel(cppSystemTime)
        out(i) = java.util.Date( ...
             cppSystemTime(i).year-1900, ...
             cppSystemTime(i).month-1, ...
             cppSystemTime(i).day, ...
             cppSystemTime(i).hour, ...
             cppSystemTime(i).minute, ...
             cppSystemTime(i).second).getTime + cppSystemTime(i).milliseconds;     
    
    end
end

